
POST http://localhost:8080/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxLHRlc3QxQG1pdS5lZHUiLCJpc3MiOiJNSVUiLCJyb2xlcyI6IltBRE1JTiwgVVNFUl0iLCJpYXQiOjE2OTcyNTcyNTEsImV4cCI6MTY5NzM0MzY1MX0.mdgpYrxp3QwKByiQRoWIroARfjXqw9QP2-uGK1RT5WwzHwDYtdDJTJ7-Oy2FdhfPgfkWfb1oJgwgad3P0aUR0g

{
  "email": "test4@miu.edu",
  "password": "123456",
  "roles": [
    {
      "id": 2,
      "name": "USER"
    }
  ]
}

###
GET http://localhost:8080/users
#Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI0LHRlc3Q0QG1pdS5lZHUiLCJpc3MiOiJNSVUiLCJyb2xlcyI6IltVU0VSXSIsImlhdCI6MTY5NzMxNjkyNSwiZXhwIjoxNjk3NDAzMzI1fQ.pzDfDLyS3N-qdUYH_-MKGHm43UKFXpr-D7yP66vpjDnvg_nru7r5casHewjfVeku-cfIgJ4u3DTKF7a7pfkysQ
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxLHRlc3QxQG1pdS5lZHUiLCJpc3MiOiJNSVUiLCJyb2xlcyI6IltBRE1JTiwgVVNFUl0iLCJpYXQiOjE2OTczMTc2MjYsImV4cCI6MTY5NzQwNDAyNn0.xJ92-5KBQLM7SKsA4l5c4r0YZCsdKJTWI6tp_5oPNoFULFpIfHQDgkzDo5rg9HYXF-KoShncKxrlc6xZiqI_hQ